### ISSUE TITLE
mockito 3.2 support

### ISSUE THREAD

**Issue by pjfanning** [scalatest/scalatestplus-mockito#11]
Thanks for releasing the mockito-1-10 jar. Would it be possible to release a mockito-3-2 jar too?

mockito 3.2.4 does seem to work ok with scalatestplus mockito-1-10 but eventually, mockito will probably end up with an incompatible change

**Comment by cheeseng** [comment]
@pjfanning  Sounds like a good idea, I shall try to see if it works.

Cheers.

**Comment by cheeseng** [comment]
@pjfanning Fyi I released a version for scalatest 3.1 and mockito 3.2, you can give it a try.

**Comment by pjfanning** [comment]
Thanks @cheeseng - I tried the new release and it works great.

**Comment by jfuentescpp** [comment]
Should this issue be closed?
